[build]
  command = "npm run assets && npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"

[[redirects]]
  from = "https://somkidvittaya.netlify.app/*"
  to = "https://somkidvittaya.ac.th/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/th/*"
  to = "/:splat"
  status = 301
