phone: (+66)38-611251
email: mail@somkidvittaya.ac.th
address: 80/5 ถ.หลังวัดป่าประดู่ ต.ท่าประดู่ อ.เมืองระยอง จ.ระยอง 21000 ประเทศไทย
facebook: https://www.facebook.com/somkidvittaya/
instagram: https://www.instagram.com/somkidvittaya_school/
youtube: https://www.youtube.com/@SomkidvittayaSchool
tiktok: https://www.tiktok.com/@somkidvittaya
line: "@404hylms"
portal_url: https://sv-portal.somkidvittaya.ac.th
